export enum EnumType {
    GET_NEWS = 'GET_NEWS',
    LOADING_NEWS = 'LOADING_NEWS',
    ERRORS_NEWS = 'ERRORS_NEWS',
    CLEAR_NEWS = 'CLEAR_NEWS',
    INFO_NEWS = 'INFO_NEWS',
    LOADING_INFO_NEWS = 'LOADING_INFO_NEWS',
    ERRORS_INFO_NEWS = 'ERRORS_INFO_NEWS'
}